### ISSUE TITLE
Brackets 1.10 from edge fails to launch

### ISSUE THREAD

**Issue by popey** [snapcrafters/brackets#2]
On my 16.04 system brackets fails to launch. 

```
alan@hal:~$ snap info brackets
name:      brackets
summary:   "Brackets is a modern code editor for HTML, CSS and JavaScript."
publisher: snapcrafters
description: |
  Brackets is an open-source editor for web design and development
  built on top of web technologies such as HTML, CSS and JavaScript.
  The project was created and is maintained by Adobe, and is released
  under an MIT License.
  
commands:
  - brackets
tracking:    stable
installed:   1.9 (2) 142MB classic
refreshed:   2017-07-11 09:40:10 +0100 BST
channels:              
  stable:    1.9  (2)  142MB classic
  candidate: 1.9  (2)  142MB classic
  beta:      1.9  (2)  142MB classic
  edge:      1.10 (10) 154MB classic
alan@hal:~$ snap refresh brackets --edge
brackets (edge) 1.10 from 'snapcrafters' refreshed
alan@hal:~$ brackets 
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/com.canonical.unity-gtk-module.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.a11y.applications.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.a11y.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.a11y.keyboard.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.a11y.magnifier.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.a11y.mouse.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.app-folders.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.background.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.datetime.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.default-applications.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.enums.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.input-sources.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.interface.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.lockdown.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.media-handling.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.notifications.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.peripherals.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.privacy.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.screensaver.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.search-providers.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.session.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.sound.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.thumbnail-cache.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.thumbnailers.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.wm.keybindings.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.desktop.wm.preferences.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.system.locale.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.system.location.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gnome.system.proxy.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gtk.Settings.ColorChooser.gschema.xml': File exists
ln: failed to create symbolic link '/home/alan/snap/brackets/10/.local/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml': File exists
/snap/brackets/10/opt/brackets/brackets: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```
